// Generated by CoffeeScript 1.9.3
(function() {
  window.log = function(val) {
    return $('body').append("<div>" + (JSON.stringify(val)) + "</div>");
  };

  window.onerror = function(errorMsg, url, lineNumber) {
    log("Error occured at (" + lineNumber + "): " + errorMsg);
    return false;
  };

}).call(this);
