// Generated by CoffeeScript 1.9.3
(function() {
  var $cost, $error, $form, $kn, $main, $secondary, $values, addDisplayValueProvider, addErrorProvider, addValueProvider, calculateCost, calculateDifficulty, clearDisplayValues, clearErrorMessage, costMultipliers, difficultyModifiers, displayValueProvider, errorProvider, exportData, getFormData, getHtmlDifficultyModifier, getHtmlSpecialModifier, getNumber, init, renderAllSpecialModifiers, renderCost, renderDifficulty, renderModifiers, renderSimpleValue, renderSpecialModifier, specialDifficultyModifiers, t;

  t = parser.t, addErrorProvider = parser.addErrorProvider, addValueProvider = parser.addValueProvider, difficultyModifiers = parser.difficultyModifiers, specialDifficultyModifiers = parser.specialDifficultyModifiers, costMultipliers = parser.costMultipliers, calculateDifficulty = parser.calculateDifficulty, calculateCost = parser.calculateCost, addDisplayValueProvider = parser.addDisplayValueProvider;

  $main = $('#main_container_field');

  $secondary = $('#secondary_container_field');

  $kn = $('#kn_container_field');

  $cost = $('#cost_container_field');

  $error = $('#error_container_field');

  $values = $('#values_container_field');

  $form = $('#form_data');

  errorProvider = function(errorMessage) {
    return $error.html("Hiba: <span>" + errorMessage + "</span>");
  };

  getNumber = function(label) {
    return prompt("Írj be egy számot (" + label + ")!", 0);
  };

  displayValueProvider = function(key, label, value) {
    return $values.append("<div>" + label + "</span>: <span class='simple_value'>" + value + "</div>");
  };

  addValueProvider('getNumber', getNumber);

  addErrorProvider(errorProvider);

  addDisplayValueProvider(displayValueProvider);

  parser.init();

  clearDisplayValues = function() {
    return $values.html('');
  };

  clearErrorMessage = function() {
    return $error.html('');
  };

  getHtmlDifficultyModifier = function(type, names) {
    var html;
    html = "<div class='pure-control-group'><label for='id_" + type + "'>" + (t(type)) + ":</label> ";
    html += "<select id='id_" + type + "' name='" + type + "'>";
    html += _(names).keys().reduce((function(sum, key) {
      return sum + "\n<option value='" + key + "'>" + (t(key)) + "</option>";
    }), '');
    return html += "</select></div>";
  };

  renderModifiers = function() {
    var content;
    content = _(difficultyModifiers).reduce((function(res, modifiers, name) {
      return res + "\n" + (getHtmlDifficultyModifier(name, modifiers));
    }), '');
    return $main.html(content);
  };

  getHtmlSpecialModifier = function(name, effect, selectedValue) {
    return "<label class='pure-radio' for='id_" + name + "_" + effect + "'> <input id='id_" + name + "_" + effect + "' type='radio' name='" + name + "' value='" + effect + "' " + (effect === selectedValue ? "checked='checked'" : "") + " />  " + (t(effect)) + " </label>";
  };

  renderSpecialModifier = function(name) {
    var effects, poisonType, selectedValue;
    poisonType = getFormData("tipus_" + name);
    effects = _(costMultipliers[poisonType].hatas).keys();
    selectedValue = getFormData(name);
    if (effects.indexOf(selectedValue) === -1) {
      selectedValue = effects.first();
    }
    return effects.reduce((function(res, effectName) {
      return res + "\n" + (getHtmlSpecialModifier(name, effectName, selectedValue));
    }), '');
  };

  renderAllSpecialModifiers = function() {
    var content;
    content = _(specialDifficultyModifiers).keys().reduce((function(res, type) {
      return res + "<div class='pure-u-1-2' id='" + type + "'><legend>" + (t(type)) + "</legend> <div class='pure-controls'>" + (renderSpecialModifier(type)) + "</div></div>\n";
    }), '');
    return $secondary.html(content);
  };

  renderSimpleValue = function(labelKey, value) {
    return "<span>" + (t(labelKey)) + ": <span class='simple_value'>" + value + "</span></span>";
  };

  renderCost = function() {
    var cost;
    cost = calculateCost(getFormData());
    return $cost.html(renderSimpleValue('ar', cost));
  };

  renderDifficulty = function(item) {
    var difficulty, value;
    difficulty = calculateDifficulty(getFormData(), $(item).prop('name'));
    value = difficulty ? difficulty : 'Hiba!';
    return $kn.html(renderSimpleValue('kn', value));
  };

  getFormData = function(attr) {
    var data, ref;
    data = $form.serializeArray();
    if (!attr) {
      return data;
    }
    return (ref = _(data).find({
      name: attr
    })) != null ? ref.value : void 0;
  };

  exportData = function() {};

  init = function() {
    renderModifiers();
    renderAllSpecialModifiers();
    renderDifficulty();
    renderCost();
    clearErrorMessage();
    clearDisplayValues();
    $('form').on('change', 'select[name^="tipus"]', function() {
      return renderAllSpecialModifiers();
    });
    return $('form').on('change', 'select, input', function(event) {
      clearDisplayValues();
      clearErrorMessage();
      renderDifficulty(event.target);
      return renderCost();
    });
  };

  init();

}).call(this);
